spring.cloud.gateway.discovery.locator.enabled=false
spring.cloud.gateway.server.webflux.routes[0].uri=lb://auth-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://catalog-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://inventory-service
spring.cloud.gateway.server.webflux.routes[3].uri=lb://cart-service
spring.cloud.gateway.server.webflux.routes[4].uri=lb://order-service
spring.cloud.gateway.server.webflux.routes[5].uri=lb://payment-service
spring.cloud.gateway.server.webflux.routes[12].uri=lb://notifications-service
