server.port=8088
spring.application.name=notifications-service
eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:http://localhost:8761/eureka}
eureka.client.register-with-eureka=${EUREKA_REGISTER:true}
eureka.client.fetch-registry=${EUREKA_FETCH:true}
eureka.instance.prefer-ip-address=${EUREKA_PREFER_IP:false}
spring.config.import=optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}

management.endpoints.web.exposure.include=health,info,prometheus
management.tracing.sampling.probability=1.0
management.otlp.metrics.export.enabled=${OTEL_METRICS_EXPORT_ENABLED:false}
management.otlp.metrics.export.url=${OTEL_EXPORTER_OTLP_METRICS_ENDPOINT:http://localhost:4318/v1/metrics}
management.otlp.tracing.export.enabled=${OTEL_TRACES_EXPORT_ENABLED:false}
management.otlp.tracing.endpoint=${OTEL_EXPORTER_OTLP_TRACES_ENDPOINT:http://localhost:4318/v1/traces}

logging.level.root=INFO
logging.level.com.example=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS,Asia/Kolkata} %-5level [trace:%X{traceId}] [%thread] [%class.%method:%line] - %msg%n

spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.consumer.group-id=notifications-service-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=io.confluent.kafka.serializers.KafkaAvroDeserializer
spring.kafka.consumer.properties.specific.avro.reader=false
spring.kafka.properties.schema.registry.url=${SCHEMA_REGISTRY_URL:http://localhost:8084}
