server.port=8082
spring.application.name=catalog-service
eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:http://localhost:8761/eureka}
eureka.client.register-with-eureka=${EUREKA_REGISTER:true}
eureka.client.fetch-registry=${EUREKA_FETCH:true}
eureka.instance.prefer-ip-address=${EUREKA_PREFER_IP:false}
spring.config.import=optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:12345}
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql
spring.data.redis.host=${SPRING_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_REDIS_PORT:6379}
spring.cache.type=${SPRING_CACHE_TYPE:simple}
spring.cache.redis.time-to-live=10m

management.endpoints.web.exposure.include=health,info,prometheus
management.tracing.sampling.probability=1.0
management.otlp.metrics.export.enabled=${OTEL_METRICS_EXPORT_ENABLED:false}
management.otlp.metrics.export.url=${OTEL_EXPORTER_OTLP_METRICS_ENDPOINT:http://localhost:4318/v1/metrics}
management.otlp.tracing.export.enabled=${OTEL_TRACES_EXPORT_ENABLED:false}
management.otlp.tracing.endpoint=${OTEL_EXPORTER_OTLP_TRACES_ENDPOINT:http://localhost:4318/v1/traces}

logging.level.root=INFO
logging.level.com.example=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS,Asia/Kolkata} %-5level [trace:%X{traceId}] [%thread] [%class.%method:%line] - %msg%n
