CREATE TABLE IF NOT EXISTS catalog_products (
    id INTEGER PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    price DOUBLE PRECISION NOT NULL,
    category VARCHAR(80) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE
);
