server.port=8888
spring.application.name=config-server
spring.profiles.active=native
spring.cloud.config.server.native.search-locations=${CONFIG_REPO_LOCATION:file:./config-repo}
management.endpoints.web.exposure.include=health,info
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS,Asia/Kolkata} %-5level [%thread] [%class.%method:%line] - %msg%n
